### ISSUE TITLE
newest update will not start.

### ISSUE THREAD

**Issue by TNWanderer** [Xjph/ObservatoryCore#100]
Using installer files appear to update installation finishes but nothing shows up, no new process starts

**Comment by nikkoura** [comment]
Same thing here, I had to remove additionnal plugins and clear settings (%LocalAppData%\ObservatoryCore) before it could start.

**Comment by Xjph** [comment]
From the release notes:

### IMPORTANT
This release also moves from .NET 5 to .NET 6. This change will break compatibility with older plugins and may cause Observatory to crash on launch if they are present.
If you wish to continue using plugins not included with this release, *continue to use your current version of Observatory* until the plugin author updates their plugins to be compatible with this version.

If this does not cover your issue then I can investigate further.

**Comment by vanderaj** [comment]
It does not start for me either. 

I tried reinstalling .NET 6.0.11 Desktop runtime from MS
I tried clearing the plugins and config directory

Is there a debug switch or build I can use to let you know what went wrong.

**Comment by vanderaj** [comment]
One thing that might be helpful is that I have 4 (yes, four) Cmdrs, and I have nearly three years' worth of journals in my journal folder. I'm assuming it only looks at the latest journal. I rarely run more than one Cmdr simultaneously, and now that Legacy Horizons is useless, I doubt I'll be doing it again.

**Comment by vanderaj** [comment]
I've installed VS 2022, and I'm struggling to build the project. Happy to work with you to document how best to build the solution, but also to build a debug build and see what's up. I have Zoom and Discord, so can screen share whilst I built the solution.

**Comment by vanderaj** [comment]
Ok, I've got the solution to build. Notably, the debug & release versions do not contain the old Evaluator and other plugins, so my guess is that the installer for this version doesn't delete the old incompatible plugins and tries to load them. I would suggest including some checks to not load outdated plugins.

**Comment by vanderaj** [comment]
So I disabled the plugins by renaming them to .old and lo and behold, Observatory now runs.

![image](https://user-images.githubusercontent.com/5029993/207759139-d9f55998-a385-4111-9937-d4f29495014d.png)

**Comment by Xjph** [comment]
Sorry about the delayed response.

Evaluator and BioInsights are not made or provided by me, which would be why my solution does not include them. New versions of them which are compatible with this release have now been made available by the author here: https://edjp.colacube.net/observatory
