### ISSUE TITLE
Issues & feature requests

### ISSUE THREAD

**Issue by DriftPunch** [Xjph/ObservatoryCore#109]
(Windows 10)

Issues:

1) Core does not retain window size or position on the desktop after being closed and re-opened.

2) Core does not retain list position when refreshed or restarted, user has to scroll all the way to bottom.

3) Triggering of voice alerts (i.e. distance from bio signal, notable body features) do not happen if game or Core have been shut down during bio collection or system exploration.

4) "Shepherd Moon" reporting seems to be broken either on the FDev side or with this app.  Ring size is reported to be much greater than what is visible in game.  After having visited several reported Shepherd Moons via Core, zero were visibly shepherd moons with ring material outside of the moon's orbit.

Feature requests:

1) Users MUST have the ability to resize columns and choose whether a column is displayed.  Absolute must have.

2) When running multiple plugins (i.e. BioInsights and Explorer)  the Core display should allow a resizable panel for each active plugin to be displayed.  Pointless to have to background the game each time Core has to be used in the foreground to read what each plugin is reporting by clicking through them.

That said, great app.  I run it continuously and it is very helpful.  Just needs a few tweaks to push it over the top.

**Comment by Xjph** [comment]
Issues:

1. It _should_, but can reset if the saved position is for some reason malformed. If you can provide a copy of your most recent `user.config` from `%localappdata%\ObservatoryCore\ObservatoryCore_Url_{install location hash}\{version}` I might be able to take a look and identify what's going wrong.
2. Lists do not necessarily persist between restarts of core, depending on plugins used and user settings. That said, the behaviour of lists and how they scroll is expected to improve very soon. I am currently in the middle of a large UI rewrite.
3. I'd like more information here. Restarting the game or Core shouldn't impact _most_ alerts. Though I can't speak to how plugins I don't provide manage theirs.
4. Large rings sometimes just aren't rendered by the game, and there's no indication in the journal files themselves if that's the case or not. All I can go on is what the journal says is there.

Features:

1. First half of this is 100% coming in the rewrite. Second half is doable, but will not be prioritised to the same degree.
2. Definitely something I'd like to do, hopefully as part of the UI rewrite or soon after.

**Comment by Xjph** [comment]
Column resizing and resizable popout panels for plugins are now done as of 1.2.
