### ISSUE TITLE
Error in Observatory Botanist while handling ScanOrganic: Value cannot be null

### ISSUE THREAD

**Issue by dmrazor** [Xjph/ObservatoryCore#111]
I get this error when starting Observatory Core. Errorlog is attached.

[ObservatoryErrorLog.txt](https://github.com/Xjph/ObservatoryCore/files/11150695/ObservatoryErrorLog.txt)

**Comment by RobinEd** [comment]
At startup I get the plugin error: 1 error encountered.
Error in Observatory Botanist while handling ScanOrganic: Value cannot be null. (Parameter 'key')
Full error details logged to ObservatoryErrorLog file in your documents folder.

**Comment by Xjph** [comment]
I believe this should be resolved now. If it is not please let me know and provide a sample of an elite dangerous log file that causes the problem.

**Comment by dmrazor** [comment]
Thanks. 

Won't be able to test this anymore though as I removed the erroneous lines from my logs. 

Regards, 
Remco 

⁣------
Verzonden van mijn mobiel​
