### ISSUE TITLE
Feature Request: Allow left menu to be shrunk into a hamburger menu

### ISSUE THREAD

**Issue by Slegnor** [Xjph/ObservatoryCore#113]
When running Observatory in a smaller scale, with a lot of plugins, nearly half of the GUI real estate is taken up with the plugin buttons:
![image](https://user-images.githubusercontent.com/11891577/235354335-dbd35244-859d-4cbe-9d90-2c55cd61dd95.png)

Suggestion is to either allow shrinking the plugin text or utilising a hamburger-style shrinkable menu aka: 

![image](https://user-images.githubusercontent.com/11891577/235354791-34e5f813-2e67-421d-b016-79d1d9477505.png)
![image](https://user-images.githubusercontent.com/11891577/235354803-f3e37a3d-7ad3-4a29-b0a9-6e79b94bd097.png)

**Comment by Xjph** [comment]
Left menu will be collapsible in the next release.

**Comment by Xjph** [comment]
https://github.com/Xjph/ObservatoryCore/pull/127
