### ISSUE TITLE
ObservatoryCore does not remember its window state when shut down

### ISSUE THREAD

**Issue by nikkoura** [Xjph/ObservatoryCore#114]
Window size and position are stored in the configuration file, but not the window state (normal / maximized / minimized).

**Comment by wbovela** [comment]
I would like to add that indeed window position and size are stored in the configuration file, and are changed accordingly, but upon the next startup some default values are returned.
Running on a second display having a different resolution that main display.

**Comment by Xjph** [comment]
This should hopefully now be resolved.
