### ISSUE TITLE
No support for multiple commanders?

### ISSUE THREAD

**Issue by Fixitman333** [Xjph/ObservatoryCore#118]
I currently have 3 Live commanders. I'm using the BioInsights plugin to keep track of biological Codex and sample completion. If I complete everything on a body with one commander, the other two also show it as completed, even though they've never been to that body before. This makes it almost completely useless for people with multiple commanders.

**Comment by Xjph** [comment]
This is an issue with the BioInsights plugin specifically, which is not maintained in this repository.

Observatory passes all journal events to plugins, including those which indicate game launch/shutdown and which commander has been loaded. I'll refer the plugin author to this issue, but will be closing it as it's out of scope for this codebase and cannot be tracked here.
