### ISSUE TITLE
Error processing Fleet Carrier Events

### ISSUE THREAD

**Issue by Elite-IGAU** [Xjph/ObservatoryCore#14]
The JSON value could not be converted to System.Int32. Path: $.SpaceUsage.FreeSpace | LineNumber: 0 | BytePositionInLine: 446.
File: Pre-read
Line (first 200 chars): { "timestamp":"2020-06-11T04:53:27Z", "event":"CarrierStats", "CarrierID":3700273408, "Callsign":"B79-Q8Q", "Name":"[IGAU] DEEP SPACE 12", "DockingAccess":"squadronfriends", "AllowNotorious":false, "F

The JSON value could not be converted to System.Int32. Path: $.SpaceUsage.FreeSpace | LineNumber: 0 | BytePositionInLine: 446.
File: Pre-read
Line (first 200 chars): { "timestamp":"2020-06-11T04:54:01Z", "event":"CarrierStats", "CarrierID":3700273408, "Callsign":"B79-Q8Q", "Name":"[IGAU] DEEP SPACE 12", "DockingAccess":"squadronfriends", "AllowNotorious":false, "F

The JSON value could not be converted to System.Int32. Path: $.SpaceUsage.FreeSpace | LineNumber: 0 | BytePositionInLine: 446.
File: Pre-read
Line (first 200 chars): { "timestamp":"2020-06-11T04:56:35Z", "event":"CarrierStats", "CarrierID":3700273408, "Callsign":"B79-Q8Q", "Name":"[IGAU] DEEP SPACE 12", "DockingAccess":"squadronfriends", "AllowNotorious":false, "F

The JSON value could not be converted to System.Int32. Path: $.SpaceUsage.FreeSpace | LineNumber: 0 | BytePositionInLine: 446.
File: Pre-read
Line (first 200 chars): { "timestamp":"2020-06-11T04:57:04Z", "event":"CarrierStats", "CarrierID":3700273408, "Callsign":"B79-Q8Q", "Name":"[IGAU] DEEP SPACE 12", "DockingAccess":"squadronfriends", "AllowNotorious":false, "F

The JSON value could not be converted to System.Int32. Path: $.SpaceUsage.FreeSpace | LineNumber: 0 | BytePositionInLine: 434.
File: Pre-read
Line (first 200 chars): { "timestamp":"2020-06-11T04:58:52Z", "event":"CarrierStats", "CarrierID":3700273408, "Callsign":"B79-Q8Q", "Name":"[IGAU] DEEP SPACE 12", "DockingAccess":"all", "AllowNotorious":false, "FuelLevel":99

The JSON value could not be converted to System.Int32. Path: $.SpaceUsage.FreeSpace | LineNumber: 0 | BytePositionInLine: 434.
File: Pre-read
Line (first 200 chars): { "timestamp":"2020-06-11T04:59:11Z", "event":"CarrierStats", "CarrierID":3700273408, "Callsign":"B79-Q8Q", "Name":"[IGAU] DEEP SPACE 12", "DockingAccess":"all", "AllowNotorious":false, "FuelLevel":99

There are 11 more errors but let's keep this window manageable.

**Comment by Xjph** [comment]
Would you mind sending any one of those complete lines? Obviously the value for "Free Space" isn't converting correctly to an `int`, but I need to see what's actually there to properly handle it.

**Comment by Xjph** [comment]
https://github.com/Xjph/ObservatoryCore/releases/tag/v0.1.320.148
