### ISSUE TITLE
Feature Request: Geology tracking similar to Botanist tab

### ISSUE THREAD

**Issue by scaryghosty** [Xjph/ObservatoryCore#170]
Just want to say I love this app... anyway, was thinking there could be another tab for Geology? Similar to the Botanist tab.

Geology takes a back seat to Exobiology in the game, however some explorers (like myself) may want to track this info similarly.

**Comment by fredjk-gh** [comment]
Thanks for the interest!! Check out https://github.com/mcmuttons/GeoPredictor from another developer...

Consider joining the discord (https://discord.gg/UJ5mWdnf) for more support, development updates and learn more about this and other plugins for Observatory Core!

**Comment by scaryghosty** [comment]
Thanks, I will check it out. Was unaware there was a Discord. I should have figured that someone made an independent plugin though...
