### ISSUE TITLE
As of the recent update, Elite Observatory does not produce audio

### ISSUE THREAD

**Issue by Vrenshrrg** [Xjph/ObservatoryCore#175]
I'd appreciate any help, the application does not announce events in audio form anymore as of the latest update (v1.0.3 Bugfix 3).

Neither the Herald plug-in nor the native voice output seem to produce any audio, at least not on any audio device I can locate. It doesn't show up in the windows volume mixer either, under any output device. I've restarted both the application and my PC. There's very little additional information I can glean I'm afraid, I'm not well versed with this type of audio issue.

**Comment by StanleyXenon** [comment]
I also found this issue.  I solved it by deleting Observatory and using a previous version and reloading all the plugins again

**Comment by Xjph** [comment]
This should hopefully now be resolved, there was an issue where loading the selected audio device could fail. Feel free to comment here and re-open if this is not the case.
