### ISSUE TITLE
Crashes on start when no sound device present

### ISSUE THREAD

**Issue by romka1977** [Xjph/ObservatoryCore#181]
After fresh install, when launching either portable or non-portable version it crashes right away.
After enabling sound device everything is normal.

May be to add exception handling with a message?

**Comment by Xjph** [comment]
Exception handling should be improved in the 1.1.3 release, but this should still be handled without throwing exceptions. Can you provide your error log?

**Comment by Xjph** [comment]
This was reported independently elsewhere, verified, and should now be handled by current versions of Observatory.
