### ISSUE TITLE
Crash on any journal update during monitoring

### ISSUE THREAD

**Issue by METROID4** [Xjph/ObservatoryCore#182]
Just started using the tool for first time, so clean install. Happens even with no plugins checked/enabled. Read All works fine even on multiple tries, but after I start monitoring, as soon as any event happens in game to update the latest journal, Observatory just instantly disappears in a crash (this happens 100% of the time even after restarts, with the same error every time). I've also tried reinstalling the program, and even just running the portable version, with 0 changes made to settings.

In Event Viewer I can see the current error:
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Text.Json.JsonException: The JSON value could not be converted to Observatory.Framework.Files.ParameterTypes.LegalStatus. Path: $.LegalState | LineNumber: 0 | BytePositionInLine: 230.

Is this a known issue with the latest game update perhaps? Let me know if you need any additional info.

**Comment by P0rtF1ssure** [comment]
I'm having the same issue. They just updated the game so it's possible that they've changed the format of a journal file and it's causing a crash.

**Comment by fredjk-gh** [comment]
A couple things that may be useful as I had no issues playing my alt last night while in the bubble. Further more we've not been inundated with reports to this effect suggesting this is not affecting everyone.

1) What version of observatory core are you using?
2) Are you pledged to a power? (My alt has never pledged to any power.)

Please consider sharing a recent journal file (either by attaching it here or sharing it with us in discord).

Thanks in advance!

**Comment by fredjk-gh** [comment]
Thanks to @METROID4 for helping with the debugging, we know that there are new LegalState values written to status.json as a result of the updated PowerPlay game mechanics. "Allied" is one such new value.

ObsCore supports the following values today:

*   Clean,
*   IllegalCargo,
*   Speeding,
*   Wanted,
*   Hostile,
*   PassengerWanted,
*   Warrant,
*   Thargoid

If you see any values other than these or other in status.json for LegalState, please report it here!

**Comment by Xjph** [comment]
This should now be resolved by the [v1.1.3 release](https://observatory.xjph.net/release#latest---v113---quick-ascendancy-bugfix). Please let me know if it persists.
