### ISSUE TITLE
Latest version triggers my virusscanner

### ISSUE THREAD

**Issue by dmrazor** [Xjph/ObservatoryCore#184]
03/11/2024 18:20
Application blocked
Path: C:\Users\<myname>\Downloads
File: ObservatorySetup.exe
Reason: Suspicious:W32/Malware.a!fsmind

Anyone else seeing this, or is it a fluke?

**Comment by Slegnor** [comment]
Happens to me with almost every release, as its a new exe and likely not yet scanned by enough PC's to be generally considered safe in AV databases.

**Comment by dmrazor** [comment]
Was a first for me, but guess it's mostly the installer that causes it. Downloaded the zip, scanned the *.exe without issues so up and running again.
