### ISSUE TITLE
[v1.1.4] Herald plugin not loading

### ISSUE THREAD

**Issue by bozho** [Xjph/ObservatoryCore#188]
Hi,

I'm using v1.1.4 and noticed today that Herald plugin is not listed when starting Observatory and Herald voice notifications are not working. The DLL is in the plugin folder, I've tried reinstalling Observatory and built-in voice notifications work fine.

Yesterday, Herald was working properly.

**Comment by Slegnor** [comment]
You might want to check the Discord, Herald has been disabled in the last 48 hours due to large API usage costs to the dev, you can still use the default TTS.  May be only temporary whilst its looked into, not sure, Discord will have more info

**Comment by Xjph** [comment]
https://forums.frontier.co.uk/threads/elite-observatory-search-your-journal-for-potentially-interesting-objects-or-notify-you-of-new-ones-on-the-fly-while-exploring.521544/post-10485312
