### ISSUE TITLE
Observatory Core 1.2.1 requires bioinsights update which doesn't exist

### ISSUE THREAD

**Issue by wbovela** [Xjph/ObservatoryCore#193]
Updated Elite Observatory Core to 1.2.1 but BioInsights plugin stuck on "Refreshing"

Core tab states BioInsights requires an update which isn't available.

slightly annoying that this is so badly timed.

**Comment by Starfire70** [comment]
Same issue with Observatory Core 1.2.2.
BioInsights functionality is critical for mine and I'm sure many others' gameplay. Rolling back.

**Comment by Xjph** [comment]
BioInsights has now been updated for Observatory 1.2.x.

https://edjp.colacube.net/observatory#download
