### ISSUE TITLE
With Elite Observatory open the pop up Taskbar won't pop

### ISSUE THREAD

**Issue by Jibsman** [Xjph/ObservatoryCore#196]
Graphics are set to Full Screen. I alt-tab to another window and move my mouse down to the Taskbar to access other apps. With Elite Observatory open the taskbar won't pop up.
If I close EO it does pop.

Core v1.2.2
I have several add-ons:
Bioinsights v1.2.0.33378
Observatory Botanist v1.1.0.33021
Colliders v1.2.0.33363
Observatory Explorer v1.1.1.33021
Stellar Overlay v1.2.0.33378

**Comment by Xjph** [comment]
This appears to be an issue with Stellar Overlay, which is not a plugin I maintain. I'll mention this to Matt but will close this issue here, as that plugin is not maintained in this repo nor by me.
