### ISSUE TITLE
Column Sort Arrow doesn't sort

### ISSUE THREAD

**Issue by DawnTreader** [Xjph/ObservatoryCore#22]
Pretty much just what the title says. The columns won't sort according to the arrow. Would like my latest Explorer data at the top.

**Comment by Tkael** [comment]
Confirmed, this is still the case in version v.0.2.22141.1531.

**Comment by kateshepard** [comment]
Confirmed to still be the case in version v.0.2.23060.2034

**Comment by kateshepard** [comment]
Great, thanks for the update! It's a great tool!
________________________________

**Comment by Xjph** [comment]
https://github.com/Xjph/ObservatoryCore/pull/127
