### ISSUE TITLE
List Filtering would be nice

### ISSUE THREAD

**Issue by DawnTreader** [Xjph/ObservatoryCore#23]
Cause then I could search for all the Nested Moons or Orbital Periods less than an hour.

**Comment by Xjph** [comment]
Unless I'm completely misunderstanding your request you can create more specific criteria for finding objects already: https://github.com/Xjph/ObservatoryExplorer/wiki/Lua-Custom-Criteria

**Comment by Tkael** [comment]
The criteria is great, but I'd like to second the request for an optional filter on the `Explorer` plugin table so that I can temporarily focus in on a specific kind of discovery (all of the Shepherd Moons I've found, for example). o7

**Comment by Xjph** [comment]
Closing this issue unless someone can present a compelling argument why disabling undesired criteria and using "read all" is insufficient for this use case.
