### ISSUE TITLE
Scroll to bottom of pane on window change

### ISSUE THREAD

**Issue by matt-g-dev** [Xjph/ObservatoryCore#24]
When switching between plugins, you currently end up at the top of the pane whilst the most recent information is at the bottom. Please change behaviour to moving to bottom of window by default. Additionally, if possible, perhaps double clicking the arrows of the scrollbar could move you to the top/bottom of the pane?

**Comment by Slegnor** [comment]
Yes, this would be nice to have.

**Comment by Xjph** [comment]
Scroll position is now remembered between tab changes. If this is an insufficient resolution feel free to comment and re-open.
