### ISSUE TITLE
Feature Request: Option to Read Logs and auto-start monitoring on launch

### ISSUE THREAD

**Issue by Slegnor** [Xjph/ObservatoryCore#27]
Feature Request: Option to Read Logs and auto-start monitoring on launch

Could be a selectable option in program settings.

Simply put, when you load the program, it would read all logs automatically and start monitoring without having to click the Read All and Start Monitoring buttons.

**Comment by Xjph** [comment]
I was about to close this as a duplicate because I was sure there was already an issue for this, but I was incorrect!

Definitely planned. In fact quite a number of the issues on this page are going to be part of a large UI improvement pass that I want to get started on very soon.

**Comment by Xjph** [comment]
Monitor on start added #42

I'm not convinced an automatic full read on launch is a good idea in light of how long it can take, and errors that may happen during it so I'm going to close this. If you feel otherwise feel free to argue your case.

**Comment by Slegnor** [comment]
I can see your point, however, Observatory had this as an option in settings, and I'd never encountered an issue with it enabled there
Would the option available to use the user to run or not on launch be the better option rather than a hard-coded manual only?
The user is ALWAYS going to have tp hit Read All before they start anyway, are they not?

**Comment by Xjph** [comment]
This has been done for a while and I forgot to close it.
https://github.com/Xjph/ObservatoryCore/tree/v0.2.22141.1531
