### ISSUE TITLE
Feature request/question: Does Observatory have a explo data value estimator similar to EDJP's?

### ISSUE THREAD

**Issue by AndrewC243** [Xjph/ObservatoryCore#29]
Came here after being on the EDJP website because the explo data value thing there kind of confused me because it didn't seem to be affected by mapping planets unless the value just assumed I would map every planet. Is there something like that for observatory, specifically evaluator, so that I can more clearly know what's being factored into the data value I see?

**Comment by Xjph** [comment]
As far as I know, the evaluator plugin reports the _maximum_ value for a body, including mapping. Enhancing Evaluator to report in more detail the vaules for mapped/unmapped is certainly *possible* though. @mgraham-dev might be able to chime in on this.

**Comment by mgraham-dev** [comment]
So evaluator should be showing a current value and a maximum value. If you have not mapped the body this should be reflected in the current value. The maximum should be the mapped value. All values assume maximum terraforming bonus, but that’s a whole other rabbit hole.

**Comment by Xjph** [comment]
Closing this as resolved, since this functionality is handled by the Evaluator plugin.
