### ISSUE TITLE
Error Message: Requested value 'bartender' was not found.

### ISSUE THREAD

**Issue by Slegnor** [Xjph/ObservatoryCore#31]
Docked at a Coriolis station today in Odyssey, now I seem to be getting this error when pressing Read All:

Requested value 'bartender' was not found.
File: Journal.211109110025.01.log
Line (first 200 chars): { "timestamp":"2021-11-09T11:48:44Z", "event":"Docked", "StationName":"Garriott Horizons", "StationType":"Coriolis", "Taxi":false, "Multicrew":false, "StarSystem":"HIP 51228", "SystemAddress":10413030

**Comment by Xjph** [comment]
Have a fix for it already here, just not in a release yet: a60cc5e04b8ea6d5426c587c2ad2d26d8dd3f09b

Hoping to have it out this coming weekend.

**Comment by Xjph** [comment]
https://github.com/Xjph/ObservatoryCore/releases/tag/v0.1.320.148
