### ISSUE TITLE
Window position in config file wrong

### ISSUE THREAD

**Issue by TribbleTrouble** [Xjph/ObservatoryCore#32]
Occasionally the window position in user.config gets set to -32000, -32000. This is off the screen and therefore Observatory does not display. I have edit the config file to get it to come back. I have two screens and the values should be

            <setting name="MainWindowPosition" serializeAs="String">
                <value>-1947, 5</value>
            </setting>
with the window displayed on the screen to my left. It does not do it always and I have not yet determine what causes it to happen. Perhaps it is shutting down the PC without closing the app.

**Comment by Xjph** [comment]
This keeps popping up from time to time, but your description of when it's happening might have finally clued me in to the cause. I think you're right about the cause, the desktop environment shutting down ahead of Observatory causes this. I'll see if I can get a permanent fix in the next release.

**Comment by Xjph** [comment]
https://github.com/Xjph/ObservatoryCore/releases/tag/v0.1.320.148
