### ISSUE TITLE
Error: The JSON value could not be converted to Observatory.Framework.Files.ParameterTypes.MicroCategory.

### ISSUE THREAD

**Issue by AliW-web** [Xjph/ObservatoryCore#39]
I selected read all, which I've not done since bug #31 was fixed - I get the attached errors.

Version: 0.1.327.2251
Plugins: 
Observatory BioInsights (v0.21.313.1557)
Observatory Botanist (v0.0.320.140)
Observatory Boxel Stats (v0.21.313.1600)
Observatory Evaluator (v0.21.291.1521)
Observatory Explorer (v0.1.327.2244)
Observatory Signal Monitor (v0.21.291.1449)
Observatory Herald (v0.0.327.2244)
Observatory Telegram Notifier (v0.21.320.142)

First error is:
The JSON value could not be converted to Observatory.Framework.Files.ParameterTypes.MicroCategory. Path: $.Category | LineNumber: 0 | BytePositionInLine: 412.
File: Journal.210722231223.01.log
Line (first 200 chars): { "timestamp":"2021-07-22T23:19:17Z", "event":"TradeMicroResources", "Offered":[ { "Name":"rdx", "Category":"Component", "Count":14 }, { "Name":"phneutraliser", "Name_Localised":"pH Neutraliser", "Cat
[ObsErrors.txt](https://github.com/Xjph/ObservatoryCore/files/7591588/ObsErrors.txt)

**Comment by Xjph** [comment]
Clearly I need to start putting more of the journal line in the error message. Can you provide the full journal line for any of those events?

**Comment by AliW-web** [comment]
[Journal.210722231223.01.log](https://github.com/Xjph/ObservatoryCore/files/7594054/Journal.210722231223.01.log)
Here you go :-)

**Comment by parduz** [comment]
Happened to me, just installed the last version:

`The JSON value could not be converted to Observatory.Framework.Files.ParameterTypes.CrimeType. Path: $.CrimeType | LineNumber: 0 | BytePositionInLine: 94.
File: Journal.211004002230.01.log
Line: { "timestamp":"2021-10-03T22:46:18Z", "event":"CommitCrime", "CrimeType":"onFoot_dataTransfer", "Faction":"Future of Arro Naga", "Fine":500 }

The JSON value could not be converted to Observatory.Framework.Files.ParameterTypes.CrimeType. Path: $.CrimeType | LineNumber: 0 | BytePositionInLine: 94.
File: Journal.211011201045.01.log
Line: { "timestamp":"2021-10-11T18:40:33Z", "event":"CommitCrime", "CrimeType":"onFoot_dataTransfer", "Faction":"Future of Arro Naga", "Fine":500 }`

Running Windows 10 Italian version.

The old "Observatory.exe" has no problems. HTH

**Comment by Xjph** [comment]
Found both, should be fixed next release.

8094820ffd56be699c0c094c71d23df2323fb520
and
1bf3927acacea55fc11fdff59f1185ec06c2ee35

If you're using the installed version (not the standalone from the zip) replacing ObservatoryFramework.dll with this one might sort you both out. If it works for you guys I'll add it to the releases page.
[ObservatoryFramework.zip](https://github.com/Xjph/ObservatoryCore/files/7599131/ObservatoryFramework.zip)

**Comment by AliW-web** [comment]
That has indeed fixed the bulk of the errores I was getting (it was +77). Just ran a read all again and I've now got only 2 errors (logs attached):

The JSON value could not be converted to System.Int64. Path: $.ShipsRemote[1].ShipMarketID | LineNumber: 0 | BytePositionInLine: 498.
File: Journal.210910205433.01.log
Line (first 200 chars): { "timestamp":"2021-09-10T23:17:10Z", "event":"StoredShips", "StationName":"Horrocks Vision", "MarketID":3225271296, "StarSystem":"Barotrites", "ShipsHere":[  ], "ShipsRemote":[ { "ShipID":0, "ShipTyp

The JSON value could not be converted to Observatory.Framework.Files.ParameterTypes.CrimeType. Path: $.CrimeType | LineNumber: 0 | BytePositionInLine: 101.
File: Journal.211005103835.01.log
Line: { "timestamp":"2021-10-05T10:46:47Z", "event":"CommitCrime", "CrimeType":"onFoot_carryingStolenGoods", "Faction":"Dakak Imperial Society", "Fine":12500 }

[Journal.210910205433.01.log](https://github.com/Xjph/ObservatoryCore/files/7604244/Journal.210910205433.01.log)
[Journal.211005103835.01.log](https://github.com/Xjph/ObservatoryCore/files/7604248/Journal.211005103835.01.log)

**Comment by Xjph** [comment]
Perfect. I'll get those fixed as well then update the release page and provide a new hotfix dll. Once that's done I'll close this issue.

**Comment by Xjph** [comment]
Release updated with repackaged installer, rebuilt standalone, and separate hotfix.

https://github.com/Xjph/ObservatoryCore/releases/tag/v0.1.327.2251
