### ISSUE TITLE
Pop-up notification frame oversize

### ISSUE THREAD

**Issue by as-73** [Xjph/ObservatoryCore#48]
Hi,

is there any solution for the scale of the pop-up notifaction frame/window?
The fontscale works, and the frame/window size on my first/main screen will reduce to the text size.
But on my second (game) screen only the text size will scale down correctly, the window/frame will always stay bigger.

![100](https://user-images.githubusercontent.com/61087067/146674263-6427a52f-15c6-43a4-b2b8-274d85c36b98.JPG)

![75](https://user-images.githubusercontent.com/61087067/146674267-6a3edb12-4f6b-4af2-9009-d470475a41db.JPG)

Regards

**Comment by Xjph** [comment]
I've had this reported before and wasn't able to reproduce or narrow down a cause. Are you able to provide any additional information about your setup? Number of monitors, size, resolution, and your current scaling setting on each if possible.

**Comment by as-73** [comment]
Here is my setup

Notebook - screen res. 1920x1080 - frame is okay
2. monitor (24") via HDMI - 1920x1080 , ingame res. 
what did you mean with scaling setting?

**Comment by Xjph** [comment]
Sorry for the delayed response. I mean the windows scale setting as seen here in display settings: 
![image](https://user-images.githubusercontent.com/455726/152544630-7a193c35-ad07-4beb-b45c-b98ead21d351.png)

**Comment by as-73** [comment]
![res](https://user-images.githubusercontent.com/61087067/152551608-9626dc5a-2019-409c-8669-36108b6ce3e1.JPG)

**Comment by as-73** [comment]
here the setting for the monitor where elite and Oberserv. are running
![res](https://user-images.githubusercontent.com/61087067/152552044-f6695db3-4519-44b3-8f40-160d3d4489c2.JPG)

**Comment by Xjph** [comment]
Strange, I got two separate message in my email, but only see one here. One screen is at 100%, and the other at 125%? That's kind of what I suspected and will help track down what's happening, I just wanted to confirm that for certain.

**Comment by as-73** [comment]
the first was my mistake, 125% is my notebook screen, so I have deleted that image and used the right one  :-)

**Comment by Xjph** [comment]
No mistake, I needed both. :D

**Comment by boschmaHH** [comment]
A friend of mine had almost the same issue, but only in the top-left position / not at the other three. Just let me know if you need more details ... I will ask him to provide.

**Comment by Xjph** [comment]
Observatory has moved to a new UI framework which has hopefully addressed this. Closing until I see reports to the contrary.
