### ISSUE TITLE
Switch Option to only display current system findings when moving from system to system.

### ISSUE THREAD

**Issue by mearmortal** [Xjph/ObservatoryCore#63]
Would it be possible to have a switch option to only display the current systems findings, I know you try and refresh the current system findings, but once moved to a new system, the option to refresh the list with only any new findings, all previous one removed.

Thanks.

**Comment by Xjph** [comment]
The original observatory actually had a "clear list on new system" option which hasn't been implemented yet since the rewrite. It will have to be implemented for Core on a per-plugin basis, but I can accept the issue here and make it happen for Explorer at the very least.

**Comment by DFgaming** [comment]
Hello, would absolutely love this functionality. Having Explorer show only the system I'm currently in would be awesome. :)
