### ISSUE TITLE
Feature Request: Display Colony Distance on Botany tab

### ISSUE THREAD

**Issue by fernoca** [Xjph/ObservatoryCore#67]
Any chance you can display the Colony distance after you have scanned the first plant?
I appreciate that it would be a hard coded look up and not from the logs, but would be good to see that displayed after the first scan. Currently i also have a text document open as well, for them, which i populated from the codex.

```
Aleoida		150m
Anemone		100m
Bacterium	500m
Brain Tree	100m
Cactoida	300m
Clypeus		150m
Concha		150m
Electricae	1000m
Fonticulua	500m
Frutexa		150m
Fumerola	100m
Fungoida	300m
Osseus		800m
Other		100m
Recepta		150m
Sinuous Tubers	100m
Stratum		500m
Tubus		800m
Tussock		200m
```

**Comment by Xjph** [comment]
Not a bad idea!
