### ISSUE TITLE
Question about scan.WasDiscovered and scan.WasMapped

### ISSUE THREAD

**Issue by alyyasser** [Xjph/ObservatoryCore#75]
are both values about whether it was discovered and/or mapped by "me" or by everyone else?

was thinking about writing my own script to give notification about body's discovered and mapped status, so i won't miss "first map" chance. anyway, i just want to confirm it, since the description kinda ambiguous for me.

**Comment by Xjph** [comment]
By anyone at all, whether it be someone else, or you on a previous visit to the system.

**Comment by alyyasser** [comment]
hmm, could you expand the API to distinguish it between scanned/discovered by anyone else, and another one for scanned/discovered by me?

**Comment by Xjph** [comment]
No, that information is not written to the journal. The API isn't mine to expand, you'd have to ask Frontier.
