### ISSUE TITLE
Update has a problem with plugins

### ISSUE THREAD

**Issue by DawnTreader** [Xjph/ObservatoryCore#88]
After updating and opening the program I get this...
![Screenshot 2022-06-18 112035](https://user-images.githubusercontent.com/40881301/174451701-fc332f65-90c7-4db6-b561-67c7d51a9618.png)
![Screenshot 2022-06-18 112105](https://user-images.githubusercontent.com/40881301/174451659-bcadc590-3bcc-4919-80a9-022a97b802dc.png)
I closed and reopened and it did the same thing. The program eventually opens. If I hit the read all it does another set of the messages, but even at the first opening it creates 145 entries.
![Screenshot 2022-06-18 113016](https://user-images.githubusercontent.com/40881301/174451805-f9782377-9fe0-46ea-998b-79f02b4d9528.png)

**Comment by Slegnor** [comment]
I reported the same issue [#87](https://github.com/Xjph/ObservatoryCore/issues/87) but realised it was not ObservatoryCore but one of MattG's plugins from [Here](https://edjp.colacube.net/observatory#download) being outdated, updated those plugins, and it resolved it

**Comment by DawnTreader** [comment]
> I reported the same issue ([#87](https://github.com/Xjph/ObservatoryCore/issues/87)) but realised it was not ObservatoryCore but one of MattG's plugins from [Here](https://edjp.colacube.net/observatory#download) being outdated, updated those plugins, and it resolved it. Check you’ve updated those plugins as well, if you use them.

Yeah, no. This is a problem right from the get go. I uninstalled and made sure that the whole directory was gone, after backing up the original. Then downloaded and installed from the latest file. I then started the program and got the same issue. At least one of the 4 packaged plugins is causing this error.

I have my copy of the tool installed at E:\Elite Observatory, is that a problem? I get this once the system is loaded.
![image](https://user-images.githubusercontent.com/40881301/174503222-c949e1e2-bfd7-4c17-a892-a31384b5e7d2.png)
I am guessing that Herald and Telegram don't have an entry along the left side.

**Comment by Slegnor** [comment]
> > I reported the same issue ([#87](https://github.com/Xjph/ObservatoryCore/issues/87)) but realised it was not ObservatoryCore but one of MattG's plugins from [Here](https://edjp.colacube.net/observatory#download) being outdated, updated those plugins, and it resolved it. Check you’ve updated those plugins as well, if you use them.
> 
> Yeah, no. This is a problem right from the get go. I uninstalled and made sure that the whole directory was gone, after backing up the original. Then downloaded and installed from the latest file. I then started the program and got the same issue. At least one of the 4 packaged plugins is causing this error.
> 
> I have my copy of the tool installed at E:\Elite Observatory, is that a problem? I get this once the system is loaded. ![image](https://user-images.githubusercontent.com/40881301/174503222-c949e1e2-bfd7-4c17-a892-a31384b5e7d2.png) I am guessing that Herald and Telegram don't have an entry along the left side.

Did you also try clearing out the folders in %appdata% and %localappdata% ?

**Comment by Xjph** [comment]
https://github.com/Xjph/ObservatoryCore/releases/tag/v0.2.22205.1832
