### ISSUE TITLE
Journal in use error message

### ISSUE THREAD

**Issue by Slegnor** [Xjph/ObservatoryCore#91]
v0.2.22163.1722
![image](https://user-images.githubusercontent.com/11891577/177009189-6d7be6cb-ebf0-41af-9b2e-76fb985ff001.png)

Had this pop up today, also running is ED Discovery and Elite G19 System Companion, all normally run together just fine.

**Comment by Xjph** [comment]
https://github.com/Xjph/ObservatoryCore/releases/tag/v0.2.22205.1832
