### ISSUE TITLE
Sinuous Tubers - BioInsights

### ISSUE THREAD

**Issue by swissbear** [Xjph/ObservatoryCore#95]
Im cruising in the galctic center region and I found some Sinuous Tubers - they appear on planets without atmosphere but biological signals. But BioInsights did not gave me a mention.

I guess its not yet implemented or somehow gets lost as its bio but no atmosphere.

Thanks for fixing it eventually

**Comment by Xjph** [comment]
BioInsights is neither maintained by me nor is in this repository. Closing.
