### ISSUE TITLE
Error popup from plugin Explorer

### ISSUE THREAD

**Issue by blzsnemeth** [Xjph/ObservatoryCore#97]
Hi,
For a few weeks i have this issue. Hopefully someone will know what this could be.
![ObservatoryCore_error](https://user-images.githubusercontent.com/114026751/191358665-c2f2f0c0-28b9-4708-b21c-3cfaf104e280.png)
Error comes up when:
- starting software with setting checked: read previous system on startup
- when entering a system and discovering bodies. In this case one after the other while they are being discovered.

Did try but not worked:
- disabling each plugin one at a time
- disabling each options in explorer plugin one at a time
- uninstalling, deleting every trace of the software and reinstalling
- searched web for possible solutions but found nothing

**Comment by Xjph** [comment]
I'd need a copy of your journal logs or the ObservatoryErrorLog file in order to investigate this. Close but will re-open if I get the necessary files.

Yes, I know this is an old issue, sorry I didn't respond more quickly.
